export const checks={need_check:'Is the requested outcome understood?',evidence_check:'Is the relevant evidence independently checked?',authority_check:'Is the specific action currently authorized?',boundary_check:'Are each participant’s conditions still satisfied?',time_check:'Is the time evidence sufficient for this action now?',receiver_check:'Can the receiver check and accept this action?'};
export function assess(state,path='evaluate'){
 const keys=Object.keys(checks);const malformed=!state||keys.some(k=>!['PASS','FAIL','UNKNOWN'].includes(state[k]));
 const failed=malformed?[]:keys.filter(k=>state[k]==='FAIL'),unknown=malformed?keys:keys.filter(k=>state[k]==='UNKNOWN');
 if(path==='stop')return {signal:'STOP',explanation:'You can decline or stop. Retain the work and record the reason in your own system.',requirements:'Do not continue the declined action. Decide locally who must be informed, under your existing permission.'};
 if(path==='counter')return {signal:'COUNTER',explanation:'Propose different terms without executing the original action. No other participant’s conditions have changed.',requirements:'Specify the change, its cost, ownership and expiry. Each affected participant must agree; then check again.'};
 if(path==='refer')return {signal:'REFER',explanation:'Consider another participant without transferring the task, private information or permission yet.',requirements:'Check that you may share the minimum needed information and that the recipient is willing and authorized to help.'};
 if(path==='reverify')return {signal:'REVERIFY',explanation:'Ask for a bounded check or clarification. Keep the original work and the unanswered questions.',requirements:'Seek a redacted example or public evidence where possible. Set a retry limit. A fresh timestamp cannot repair expired authorization.'};
 if(failed.length)return {signal:'STOP',explanation:'At least one required condition is not satisfied. The original action remains blocked; the work is retained.',requirements:'Failed: '+failed.map(k=>checks[k]).join(' ')+' You may explore a counterproposal or referral without executing this action.'};
 if(malformed||unknown.length)return {signal:'REVERIFY',explanation:'Some required checks are unknown or malformed. Choosing to accept does not make them pass.',requirements:'Resolve: '+unknown.map(k=>checks[k]).join(' ')+' Do not execute while required checks remain unresolved.'};
 return {signal:'PROCEED',explanation:'All listed checks are marked satisfied by you. This is a worksheet illustration, not a verified grant or an executed action.',requirements:'The actor and receiver must still perform their real checks at the action boundary, including current authority and time. The page has verified none of those facts.'};
}
